version: "3"

services:
  web:
    build:
      context: ./web
    networks:
      - app-network
  proxy:
    build:
      context: ./proxy
    depends_on:
      - web
    networks:
      - app-network
  tor:
    build:
      context: ./tor
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
